name: Verify Payment Service Image

on:
  push:
    branches:
      - main

jobs:
  test_image:
    runs-on: [self-hosted, quickbite]

    permissions:
      packages: read
      contents: read

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5

      - name: Đăng nhập GHCR
        run: |
          docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Pull và verify Docker Image
        run: |
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/payment-service:1.0.0"

          echo "Using image: $IMAGE_TAG"

          docker pull "$IMAGE_TAG"

          docker run -d \
            --name verify_payment_service \
            -p 8080:8080 \
            "$IMAGE_TAG"

          sleep 5

          docker ps

          docker rm -f verify_payment_service || true
